# version: "3"
services:
  service1:
    build: ./service_1
    container_name: service1
    ports:
      - "8080:8080"

  service2:
    build: ./service_2
    container_name: service2
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
